name: Build example

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "example/**"

jobs:
  build:
    name: Build example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: subosito/flutter-action@v2.23.0
        with:
          cache: true
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          workingDir: example
          baseHref: /flutter_map_animations/
